####
# This Dockerfile is used in order to build a container that runs the glow-ui application in Vite dev mode.
#
# Before building the container image run:
#
# npm ci
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.dev -t glow-ui-dev .
#
# Then run the container using:
#
# docker run -i --rm -p 5173:5173 glow-ui-dev
#
# This image runs the Vite dev server so the UI can be developed with hot reload.
#
####
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173", "--strictPort"]